baseURL: "https://dylanlaplacemermoud.github.io" 
title: Dylan Laplace Mermoud
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: articles/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3 
        - name: Resume
          url: cv_laplace_mermoud.pdf
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a postdoctoral researcher in quantum algorithms at ENSTA - Institut Polytechnique de Paris."
    author: Dylan Laplace Mermoud
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dylan Laplace Mermoud
          subtitle: "I am a postdoctoral researcher in quantum algorithms at the mathematics department of ENSTA from the Institut Polytechnique de Paris. I am also affiliated with the combinatorial optimization team in the CEDRIC lab at the Conservatoire National des Arts et MÃ©tiers. I work with Andrea Simonetto, and Sourour Elloumi. Besides quantum algorithms, my research focuses on algebraic combinatorics and cooperative game theory."
          imageUrl: "photo.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dylan Laplace Mermoud
          buttons:
            - name: Research
              url: articles/
            - name: Talks
              url: talks/
            - name: Teaching
              url: teaching/
            - name: Resume
              url: cv.pdf
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: hal
          url: https://cv.hal.science/dylan-laplace-mermoud
        - name: arXiv
          url: http://arxiv.org/a/laplacemermoud_d_1
        - name: orcid
          url: https://orcid.org/0000-0002-1508-9656
        # - name: CV
        #   url: cv.pdf
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=haznRHoAAAAJ&hl=fr&oi=ao
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitLab
          url: https://gitlab.com/DylanLaplaceMermoud
        - name: GitHub
          url: https://github.com/DylanLaplaceMermoud
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat
        - name: Email
          url: mailto:dylan.laplace.mermoud@gmail.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        mask_icon: "/safari-pinned-tab.svg"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dylan Laplace Mermoud"
      icon: logo2.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
